apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ficct-emergencias
type: Opaque
stringData:
  POSTGRES_DB: diagramador
  POSTGRES_USER: diagramador
  POSTGRES_PASSWORD: change-me
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: change-me
  OPENAI_API_KEY: ""
  JWT_SECRET: change-me-jwt-secret
