apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ficct-emergencias
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 5656
      targetPort: 5656
      nodePort: 30656
