apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ficct-emergencias
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
